makeup1Solution/makeup1/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using makeup1.Models;
using makeup1.Repositories;
using Microsoft.AspNet.Identity;
using makeup1.ViewModels;
//using makeup1.ViewModels;

namespace makeup1.Controllers
{
    public class PhotoController : Controller
    {
        // Hann ætti að hafa photo repository 
        IPhotoRepository photoRepository;
        //PhotoRepository repo = new PhotoRepository();


        public PhotoController()
        {
            photoRepository = new PhotoRepository();
        }

        // Test constructor, takes a repository as argument.
        public PhotoController(IPhotoRepository photoRepo)
        {
            photoRepository = photoRepo;
        }

            
        //The parameter is the user id, then we will find all
        //photos with the same user id
        public ActionResult MyProfile()
        {
            //PhotoViewModel viewModel = new PhotoViewModel();

            string userId = User.Identity.GetUserId();

            PhotoRepository rep = new PhotoRepository();

            UsersAccount model = new UsersAccount();
            model.photos = rep.GetUsersPhotos(userId);
            
           // Console.WriteLine(viewModel);
            return View(model);
        }

        public ActionResult FriendsProfile(string id)
        {
            //PhotoViewModel viewModel = new PhotoViewModel();

            UserRepository userRep = new UserRepository();

            ApplicationUser user = userRep.GetUserByUsername(id);
            string loggedInUser = User.Identity.GetUserName();

            PhotoRepository rep = new PhotoRepository();

            UsersAccount model = new UsersAccount();

            model.username = id;
            model.isFollowing = userRep.IsFollowing(loggedInUser, user.UserName);
            model.photos = rep.GetUsersPhotos(user.Id);

            // Console.WriteLine(viewModel);
            return View("MyProfile", model);
        }

        public JsonResult FollowUser(string username)
        {
            PhotoRepository repo = new PhotoRepository();
            string user = User.Identity.GetUserName();
            bool resp = repo.FollowUser(user, username);

           
            return Json(resp, JsonRequestBehavior.AllowGet);
        }

        public JsonResult UnFollowUser(string username)
        {
            PhotoRepository repo = new PhotoRepository();
            string user = User.Identity.GetUserName();
            bool resp = repo.UnFollowUser(user, username);

            return Json(resp, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Upload(UploadModel model)
        {
            PhotoRepository repo = new PhotoRepository();
            model.userid = User.Identity.GetUserId();
            bool resp = repo.AddPhoto(model);

            return Json(resp, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddPhoto(string photoUrl, string comment)
        {
            // test if parameters are correct
            string userId = User.Identity.GetUserId();
            var p = new Photo { photoUrl = photoUrl, Caption = comment , DateCreated = DateTime.Now, UserId = userId };
            photoRepository.Add(p);
           // var model = photoRepository.Add(new Photo(photoUrl,comment,userId));

            return RedirectToAction("MyProfile", "Home");
        } 


        // GET: /Photo/
        /*
        public ActionResult Index()
        {
            List<Photo> mockPhotos = new List<Photo>();

            Photo photo1 = new Photo("http://www.pictures4cool.com/media/images/picture-wallpaper.jpg");
            photo1.ID = 0;
            
            Photo photo2 = new Photo("http://globe-views.com/dcim/dreams/photo/photo-06.jpg");
            photo2.ID = 1;
           
            mockPhotos.Add(photo1);
            mockPhotos.Add(photo2);

            return View(mockPhotos);
        }*/
	}
}

makeup1Solution/makeup1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Main.css" rel="stylesheet" />
</head>

<body>
    @if (Request.IsAuthenticated)
    {
         <div class="login">
           @Html.Partial("_LoginPartial")
         </div>
    }

    <div class="logo">
        <a href='@Url.Action("Index", "Home")'>
            <img id="logo" src="http://i296.photobucket.com/albums/mm180/marinjonsdottir2/logo_zpsr2yatmf8.jpg" alt="makeup logo" />
        </a>
    </div>

    <div class="navbar-inverse navbar-fixed-top>
        <div class=" container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Fréttaveita", "Index", "Home")</li>
                <li>@Html.ActionLink("Um síðuna", "About", "Home")</li>
                @if (Request.IsAuthenticated)
                {
                    <li>@Html.ActionLink("Mín síða", "MyProfile", "Photo")</li>
                    <li>@Html.ActionLink("Tilboð", "Offer", "Home")</li>
                    <li>@Html.ActionLink("Förðunarfræðingar", "Artist", "Home")</li>

                }
            </ul>

            @if (Request.IsAuthenticated)
{
    <form action="/" method="post">
        <input type="text" class="form-control pull-right search-box" placeholder="Leita.." id="searchBox" />
    </form>
}
        </div>
    </div>
    </div>
    <div class="container body-content">
        <div id="searchResults">

        </div>
        @RenderBody()
        <hr />

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)

    <script src="~/Scripts/MakupScript.js/Script.js"></script>

</body>
</html>